import { createSlice } from '@reduxjs/toolkit'

const catalogosSlice = createSlice({
  name: 'catalogos',
  initialState: [
    {
      programa: 1,
      nomedofilme: 'Dádiva ',
      direcao: 'Evelyn dos Santos',
      estado: 'São Paulo, SP',
      minutos: 6,
      link: 'https://youtu.be/mJygIYO7OjA',
      pic: '/fotos/4.jpg',
      votacao: 'https://forms.gle/fQaVx3Ljx3ikSTwD6',
    },
    {
      programa: 1,
      nomedofilme: 'O Homem Atrás da Janela',
      direcao: 'Naum Roberto Gomes',
      estado: 'Pelotas, RS',
      minutos: 8,
      link: 'https://youtu.be/8zckL3gFmpc',
      pic: '/fotos/5.jpg',
      votacao: 'https://forms.gle/zTieW6sN8UVqDNwt8',
    },
    {
      programa: 2,
      nomedofilme: 'Meninos Rimam',
      direcao: 'Lucas Nunes',
      estado: 'São Carlos, SP',
      minutos: 20,
      link: 'https://youtu.be/XNCOx3t__gQ',
      pic: '/fotos/6.jpg',
      votacao: 'https://forms.gle/J9Znza9fnR6FrwZr5',
    },
    {
      programa: 2,
      nomedofilme: 'Caminhos da Noite',
      direcao: 'Douglas Oliveira',
      estado: 'Aracaju, SE',
      minutos: 19,
      link: 'https://youtu.be/D1kllrQwSWc',
      pic: '/fotos/8.jpg',
      votacao: 'https://forms.gle/JUVV7f92Wu6PYNCM9',
    },
    {
      programa: 2,
      nomedofilme: 'Onde nascem os Deuses',
      direcao: 'Henrique DPK',
      estado: 'Salto, SP',
      minutos: 15,
      link: 'https://youtu.be/dxcPG5qHK3U',
      pic: '/fotos/9.jpg',
      votacao: 'https://forms.gle/mnvLKtf45mEYkGi16',
    },
    {
      programa: 3,
      nomedofilme: 'Cinema Contemporâneo',
      direcao: 'Felipe André Silva',
      estado: 'Recife, PE',
      minutos: 5,
      link: 'https://youtu.be/vnI68VBRd4E',
      pic: '/fotos/11.jpg',
      votacao: 'https://forms.gle/uG1qUvvFrh5Coa6k7',
    },
    {
      programa: 3, 
      nomedofilme: 'A noite se tornara ainda mais escura',
      direcao: 'Bianca Ellen, Lux Farr, Isa Vitório, Arara, Fran Xyk',
      estado:'Fortaleza, CE',
      minutos: 12 ,
      link: 'https://youtu.be/0SCbA1C7RlU',
      pic: '/fotos/12.jpg',
      votacao: 'https://forms.gle/kZJJE1xkHwhwtQ346',
    },
    {
      programa: 3,
      nomedofilme: 'Nó no Couro',
      direcao: 'Mariana Martins',
      estado: 'Juiz de Fora, MG',
      minutos: 14,
      link: 'https://youtu.be/OUqNo3MmphE',
      pic: '/fotos/13.jpg',
      votacao: 'https://forms.gle/RdYMypy4P4ntsNqZ9',
    },
    {
      programa: 4,
      nomedofilme: 'Oríki',
      direcao: 'Pâmela Peregrino',
      estado: 'Porto Seguro, BA',
      minutos: 6,
      link: 'https://youtu.be/XUm131QQQ5Y',
      pic: '/fotos/15.jpg',
      votacao: 'https://forms.gle/GTAVp1PL3G1APzU69',
    },
    {
      programa: 4,
      nomedofilme: 'Joãosinho da Goméa - O Rei do Candomblé',
      direcao: 'Janaina Oliveira ReFem e Rodrigo Dutra',
      estado: 'Duque de Caxias/RJ',
      minutos: 14,
      link: 'https://youtu.be/9_RrLbhgdAM',
      pic: '/fotos/16.jpg',
      votacao: 'https://forms.gle/nXQoDvMb5EcoADZU6',
    },
    {
      programa: 4,
      nomedofilme: 'Guardião dos Caminhos',
      direcao: 'Milena Manfredini',
      estado: 'Rio de Janeiro, RJ',
      minutos: 3,
      link: 'https://youtu.be/FrGjCwZUITo',
      pic: '/fotos/17.jpg',
      votacao: 'https://forms.gle/xUhCVVzPYmQz8qCn8',
    },
    {
      programa: 4,
      nomedofilme: 'Princesa do meu lugar',
      direcao: 'Pablo Monteiro',
      estado: 'Sao Luis, MA',
      minutos: 15,
      link: 'https://youtu.be/AP7l-GF55h8',
      pic: '/fotos/18.jpg',
      votacao: 'https://forms.gle/ijaMnCgPrzt1UWAo8',
    },
    {
      programa: 5,
      nomedofilme: 'Práticas do Absurdo',
      direcao: 'Alexander S. Buck',
      estado: 'Vitória, ES',
      minutos: 16,
      link: 'https://youtu.be/7zmA1_2XzSE',
      pic: '/fotos/20.jpg',
      votacao: 'https://forms.gle/GGo2qbx8kcxoA1mz8',
    },
    {
      programa: 5,
      nomedofilme: 'Rio das Almas e Negras Memórias',
      direcao: 'Taize Inácia e Thaynara Rezende',
      estado: 'Goiânia e Pirenópolis, GO',
      minutos: 20,
      link: 'https://youtu.be/CBRcn7jsfbs',
      pic: '/fotos/21.jpg',
      votacao: 'https://forms.gle/jk93M9xou4bQShnY7',
    },
    {
      programa: 5,
      nomedofilme: 'marvin.gif PART II',
      direcao: 'Marvin Pereira',
      estado: 'Cachoeira, BA',
      minutos: 4,
      link: 'https://youtu.be/GtXTrFwiY9A',
      pic: '/fotos/22.jpg',
      votacao: 'https://forms.gle/ohNPNdfmeTV7WrBP8',
    },
    {
      programa: 5,
      nomedofilme: 'Chamada a Cobrar',
      direcao: 'Edson Ferreira',
      estado: 'Vitoria, ES',
      minutos: 19,
      link: 'https://youtu.be/xcEAhmI0PVQ',
      pic: '/fotos/23.jpg',
      votacao: 'https://forms.gle/B9XcaY1yNCQLb56C8',
    },
    {
      programa: 5,
      nomedofilme: 'Ditadura Roxa',
      direcao: 'Matheus Moura',
      estado: 'Belo Horizonte, MG',
      minutos: 23,
      link: 'https://youtu.be/XXwT1GGLun8',
      pic: '/fotos/24.jpg',
      votacao: 'https://forms.gle/FBRtB3ePeTsUpVa59',
    },
    {
      programa: 6,
      nomedofilme: 'Dias Felizes',
      direcao: 'André Santos',
      estado: 'Natal, RN',
      minutos: 13,
      link: 'https://youtu.be/RSP68YMj5Fc',
      pic: '/fotos/26.jpg',
      votacao: 'https://forms.gle/KGe5yk4Ws1QXqmgZ8',
    },
    {
      programa: 6,
      nomedofilme: 'Corações Encouraçados',
      direcao:'Jamile Coelho e Cintia Maria',
      estado: 'Salvador, BA',
      minutos: 15,
      link: 'https://youtu.be/Uy3ZkpEhibs',
      pic: '/fotos/27.jpg',
      votacao: 'https://forms.gle/jiKwkjEtPiBVBxAC7',
    },
    {
      programa: 6,
      nomedofilme: 'MÃEPRETA - terra, ventre e luz',
      direcao: 'Gabriel Quadros',
      estado: 'São Paulo SP',
      minutos: 6,
      link: 'https://youtu.be/RA4R0uiDrsY',
      pic: '/fotos/28.jpg',
      votacao: 'https://forms.gle/qbky57vJYG4ma4pS7',
    },
    {
      programa: 6,
      nomedofilme: 'Enquanto eu for lembrado',
      direcao: 'Állan Maia',
      estado: 'Cachoeira, BA',
      minutos: 29,
      link: 'https://youtu.be/aRnobOUm6O8',
      pic: '/fotos/29.jpg',    
      votacao: 'https://forms.gle/HFqveuMiHNKDAy4s8',
    },
    {
      programa: 7,
      nomedofilme: '23 Minutos',
      direcao: 'Rodrigo Beetz / Wesley Figueiredo',
      estado: 'Ribeirão das Neves, MG',
      minutos: 16,
      link: 'https://youtu.be/XscSsINtphw',
      pic: '/fotos/31.jpg',    
      votacao: 'https://forms.gle/1gaJh25bZHTtYVB88',
    },
    {
      programa: 7,
      nomedofilme: 'Quantos Eram pra ta?',
      direcao:'Vinícius Silva',
      estado: 'São Paulo, SP',
      minutos: 29,
      link: 'https://youtu.be/HBzTspgYtNo',
      pic: '/fotos/32.jpg',    
      votacao: 'https://forms.gle/2DS1rjjsZ1nshW5S8',
    },
    {
      programa: 7,
      nomedofilme: 'Ser Feliz No Vão',
      direcao: 'Lucas H. Rossi dos Santos',
      estado: 'Rio de Janeiro, RJ',
      minutos: 12,
      link: 'https://youtu.be/3mpYUrxW4P0',
      pic: '/fotos/33.jpg',    
      votacao: 'https://forms.gle/CxSxZ9Rz9AUB9Akv8',
    },
    {
      programa: 8,
      nomedofilme: 'Ilhas de Calor',
      direcao: 'Ulisses Arthur',
      estado: 'Maceió, AL',
      minutos: 20,
      link: 'https://youtu.be/gTaNRl6j3BI',
      pic: '/fotos/35.jpg',    
      votacao: 'https://forms.gle/wAu2jVQzTEfLMkx2A',
    },
    {
      programa: 8,
      nomedofilme: 'Para todes',
      direcao: 'Victor Hugo, Samara Garcia e equipe',
      estado: 'Rio de Janeiro, RJ',
      minutos: 13,
      link: 'https://youtu.be/5JQwHIJTQWo',
      pic: '/fotos/36.jpg',    
      votacao: 'https://forms.gle/FRC8PiZUK2zSLpPeA',
    },
    {
      programa: 8,
      nomedofilme: 'Enraizadas',
      direcao: 'Gabriele Roza e Juliana Nascimento',
      estado: 'Rio de Janeiro, RJ',
      minutos: 14,
      link: 'https://youtu.be/7DXF-YQ1Rz0',
      pic: '/fotos/37.jpg',    
      votacao: 'https://forms.gle/arPU4tmKUQGMKGXPA',
    },
    {
      programa: 9,
      nomedofilme: 'Socialights | Jorge Lafond',
      direcao: 'Noah Mancini',
      estado: 'Juiz de Fora, MG',
      minutos: 10,
      link: 'https://youtu.be/2KqxKdULtmU',
      pic: '/fotos/39.jpg',    
      votacao: 'https://forms.gle/JR1ScSpc6kWCj9eK9',
    },
    {
      programa: 9,
      nomedofilme: 'As Canções de Amor de uma Bixa Velha',
      direcao: 'André Sandino Costa',
      estado: 'Rio de Janeiro, RJ',
      minutos: 22,
      link: 'https://youtu.be/8jA22brvcdI',
      pic: '/fotos/40.jpg',    
      votacao: 'https://forms.gle/LJRW24YeDQJ1L1HY7',
    },
    {
      programa: 9,
      nomedofilme: 'Goma',
      direcao: 'Igor Vasco',
      estado: 'São Paulo, SP',
      minutos: 20,
      link: 'https://youtu.be/n0dkrkQO6Ik',
      pic: '/fotos/41.jpg',        
      votacao: 'https://forms.gle/9GBNhA7JhpKa3k7q7',
    },
    {
      programa: 9,
      nomedofilme: 'Inspirações',
      direcao: 'Ariany e equipe',
      estado: 'Rio de Janeiro, RJ',
      minutos: 18,
      link: 'https://youtu.be/cypfTAg_5q0',
      pic: '/fotos/42.jpg',        
      votacao: 'https://forms.gle/EDR56pSxqWt7xMac7',
    },
    {
      programa: 10,
      nomedofilme: 'À beira do planeta mainha soprou a gente',
      direcao: 'Bruna Barros e Bruna Castro',
      estado: 'Salvador, BA',
      minutos: 13,
      link: 'https://youtu.be/I7iy5CzF-mU',
      pic: '/fotos/44.jpg',        
      votacao: 'https://forms.gle/CujQRj37QjCKjhLUA',
    },
    {
      programa: 10,
      nomedofilme: 'Looping',
      direcao: 'Maick Hannder',
      estado: 'Belo Horizonte, MG',
      minutos: 12,
      link: 'https://youtu.be/eNdMuKZuOoA',
      pic: '/fotos/45.jpg',        
      votacao: 'https://forms.gle/uSkXVEZs8a7HpbSF8',
    },
    {
      programa: 10,
      nomedofilme: 'Ensaio',
      direcao: 'Carol Sousa e Grenda Costa',
      estado: 'Fortaleza, CE',
      minutos: 3,
      link: 'https://youtu.be/B0oNaeUKqAc',   
      pic: '/fotos/46.jpg',     
      votacao: 'https://forms.gle/6xPdmFdts6v5RGuW9',
    },
    {
      programa: 10,
      nomedofilme: 'Cão Maior',
      direcao: 'Filipe Alves',
      estado: 'Brasília, DF',
      minutos: 20,
      link: 'https://youtu.be/oF8M5ZvNUPY',
      pic: '/fotos/47.jpg',        
      votacao: 'https://forms.gle/fdMennQTGxLdvzsE9',
    },
    {
      programa: 10,
      nomedofilme: 'Naquela Época Devoraram Meus Olhos',
      direcao: 'Cleissa Regina Martins',
      estado: 'Rio de Janeiro/ Niterói, RJ',
      minutos: 4,
      link: 'https://youtu.be/vLwEBtYYURA',
      pic: '/fotos/48.jpg',        
      votacao: 'https://forms.gle/AHo7hH5UzQiiHYG77',
    },
  ]
})

export const catalogos = (state) => state.catalogos

export const getCatalogoByPrograma = (state) => (numeroDoPrograma) =>  
  state.catalogos.filter((catalogo) => catalogo.programa == numeroDoPrograma)

export const getAllProgramaNumbers = (state) => 
  new Set(state.catalogos.map(data => data.programa))


export default catalogosSlice.reducer
